### ISSUE TITLE
 Is AES-CTR mode supported?

### ISSUE THREAD

**Issue by angelshadow** [smuellerDD/acvpparser#46]
I don't see the resolution of aes-ctr mode in the implementation of backend and parser. How do I handle the payloadlen variable in the test vector?

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Dezember 2021, 03:33:27 CET schrieb angelshadow:

Hi angelshadow,

> I don't see the resolution of aes-ctr mode in the implementation of backend
> and parser. How do I handle the payloadlen variable in the test vector?

Why do you think AES-CTR should be special? It gets a:

- plaintext/ciphertext which is in struct sym_data->data

- a key which is in struct sym_data->key

- an IV (the start point for the counter) which is in struct sym_data->iv - 
this IV needs to be returned after the operation completes as it is the case 
with all other block chaining modes

Ciao
Stephan

**Comment by angelshadow** [comment]
> Am Donnerstag, 2. Dezember 2021, 03:33:27 CET schrieb an
In fact, I don't quite understand the description of aes-ctr mode in NIST acvp payloadlen description. 
“”For AES-CTR, the values supplied for this parameter refer to the bit sizes supported in the last incomplete block (less than 128 bits) of the plain or cipher text.”
If a test vector only gives you Pt = "95", payloadlen = 8, how to deal with plaintext to meet the requirements of test vector?

The payloadlen variable in the parser code should be resolved to data_ len_ bits field. How should I do of this variable with the input data(ct or pt or iv or key) in CTR mode?

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Dezember 2021, 07:51:25 CET schrieb angelshadow:

Hi angelshadow,

> > Am Donnerstag, 2. Dezember 2021, 03:33:27 CET schrieb an
> 
> In fact, I don't quite understand the description of aes-ctr mode in NIST
> acvp payloadlen description. 
 “”For AES-CTR, the values supplied for this
> parameter refer to the bit sizes supported in the last incomplete block
> (less than 128 bits) of the plain or cipher text.” If a test vector only
> gives you Pt = "95", payloadlen = 8, how to deal with plaintext to meet the
> requirements of test vector? 
> The payloadlen variable in the parser code should be resolved to data_ len_
> bits field. How should I do of this variable with the input data(ct or pt
> or iv or key) in CTR mode?

Well, the payloadlen is ALWAYS identiccal to the plaintext. The issue is that 
the plaintext is a hex string in the vector - it is of course quite difficult 
to represent, say, a 10 bit plaintext in a hex string. Just looking at the hex 
string may not give you the right information as you would treat it as 16 bits 
instead of 10 bits.

So, the payloadlen is needed.

Note, the current parser code gives you the payloadlen data in struct 
sym_data->data_len_bits
 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/acvpparser/issues/46#issuecomment-984341279


Ciao
Stephan
